name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0<3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  lottie: ^1.4.3
  modal_progress_hud_nsn: ^0.5.1
  rive: ^0.12.4



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - images/login_animation.riv
  - images/splash_animation.json
  
